The following exercises are designed to help you get familiar with the basics of numpy, pandas, and matplotlib packages. These exercises are extension of material we discuss during lecture. You can access the lecture .ipynb files to get familiar with the basics.


In order to complete this assignment, first you need to import proper packages and read data files into proper data structures. 

The __deadline__ for submitting this assignment is __Friday, Feb 19__.
Submit your solution on __Gradescope__.

# Exercises

## Numpy

Check out the Numpy-Basics file and read the documentation at http://www.numpy.org
Now it's your turn to do some practice with NumPy: 

#### 1. Create a 1-dimensional NumPy array of 100 random integers (1 pt)

1.  Find and print all the summary statistics (mean, std, median, max, min, ...)
2.  Compare the time for finding the max using python built-in functions and NumPy corresponding function
3. Create a new array that is the base-2 logarithm of your array

In [54]:
import numpy as np
randint = np.random.randint(0,101,size=100)
print("Array", randint)
print("Sum",np.sum(randint))
print("Mean",np.mean(randint))
print("Standard Deviation",np.std(randint))
print("Median",np.median(randint))
print("Maximum",np.max(randint))
print("Minimum",np.min(randint))




Array [  4  53  15  47  29  62  99  81  37  58  33  67  87  32  24  33  74  66
   9  50  68  87  21  52  12  26   3 100  52  96  71  76  98  21  65   1
  33  12  40  10  12  94  81  41  54  57  78  81  13   1  29  26  34   9
  59  46  28 100  23   2  75  26  48   6  87  63  85  67   2  68  83  85
  50  91  67  64  50  41  94  20  99  32  53  18  61  91  38  33   5  13
  11  58  37  29  70  56  93   2  84  31]
Sum 4858
Mean 48.58
Standard Deviation 29.626062850132485
Median 50.0
Maximum 100
Minimum 1


In [56]:
%timeit max(randint)
%timeit np.max(randint)



8.58 µs ± 104 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
2.8 µs ± 7.29 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [57]:
np.log2(randint)


array([2.        , 5.72792045, 3.9068906 , 5.55458885, 4.857981  ,
       5.95419631, 6.62935662, 6.33985   , 5.20945337, 5.857981  ,
       5.04439412, 6.06608919, 6.4429435 , 5.        , 4.5849625 ,
       5.04439412, 6.20945337, 6.04439412, 3.169925  , 5.64385619,
       6.08746284, 6.4429435 , 4.39231742, 5.70043972, 3.5849625 ,
       4.70043972, 1.5849625 , 6.64385619, 5.70043972, 6.5849625 ,
       6.14974712, 6.24792751, 6.61470984, 4.39231742, 6.02236781,
       0.        , 5.04439412, 3.5849625 , 5.32192809, 3.32192809,
       3.5849625 , 6.55458885, 6.33985   , 5.357552  , 5.7548875 ,
       5.83289001, 6.28540222, 6.33985   , 3.70043972, 0.        ,
       4.857981  , 4.70043972, 5.08746284, 3.169925  , 5.88264305,
       5.52356196, 4.80735492, 6.64385619, 4.52356196, 1.        ,
       6.22881869, 4.70043972, 5.5849625 , 2.5849625 , 6.4429435 ,
       5.97727992, 6.40939094, 6.06608919, 1.        , 6.08746284,
       6.37503943, 6.40939094, 5.64385619, 6.50779464, 6.06608

#### 2. Create a 2-dimensional NumPy array of (3,4) random integers (mat1) (2 pts)

1. Create another 2-D array that is the square root of your original array (mat2)
2. Find how many values are greater than 20 using np.count_nonzero(  ) function ( you can also use np.sum( )
3. Perform a dot product between two 2-D arrays (mat3)
4. Find all the values that are less than 10 and greater than 30 in mat3

In [68]:
# 1. Create another 2-D array that is the square root of your original array (mat2)
import numpy as np
mat1 = np.random.randint(100,size=(3,4))
print("Array", mat1)
mat2 = np.sqrt(mat1)
print(mat2)

Array [[29 41 88 54]
 [30 36 71 89]
 [22  6 71 75]]
[[5.38516481 6.40312424 9.38083152 7.34846923]
 [5.47722558 6.         8.42614977 9.43398113]
 [4.69041576 2.44948974 8.42614977 8.66025404]]


In [73]:
# 2. Find how many values are greater than 20 using np.count_nonzero(  ) function ( you can also use np.sum( )
count = np.count_nonzero(mat1 > 20)
print("In mat1:",count)

In mat1: 11


In [81]:
# 3. Perform a dot product between two 2-D arrays (mat3)
mat2 = np.random.randint(100,size=(4,2))
mat3 = np.dot(mat1,mat2)
print(mat3)

[[ 5772 13816]
 [ 5455 14183]
 [ 2059 11595]]


In [106]:
# 4. Find all the values that are less than 10 and greater than 30 in mat3
print(mat3[mat3<10])
print(mat3[mat3>30])

[]
[ 5772 13816  5455 14183  2059 11595]


## Pandas

Check out the pandas-basics file on Blackbaord. 
pandas documentation is very detailed and useful and contains a [short tutorial](https://pandas.pydata.org/pandas-docs/stable/user_guide/10min.html). You can also check this [Cheatsheet](https://github.com/pandas-dev/pandas/blob/master/doc/cheatsheet/Pandas_Cheat_Sheet.pdf)



Now it's your turn to do some exercises and get familiar with Python. First, you are going to answer some questions about the movies dataset we already explored:

####  3. Pandas basics with movies_by_year data (2 pts)

Download the "movies_by_year.csv" file from Blackboard _(Weekly content : Week 6)_

1. Get a quick statistical profile of Total_Gross column
2. Get the summary statistics (mean,max,min,std) of Total_Gross for movies that were highest grossing movie of the year during 1995 - 2005
3. Do the same thing for movies during 2005-2015 period
4. What are some insights you gain from this comparison?




In [3]:
pd.csv(movies_by_year.)

In [4]:
# Your code goes here 

####  4. Pandas basics with risk dataset (2 pts)

Download the "Risk.csv" file from Blackboard _(Weekly content : Week 6)_

1. Find the minimum and maximum values of income
2. Find the mean income based on gender
3. Draw the histogram of income distribution based on gender


In [5]:
# Your code goes here 

In [6]:
# Your code goes here 

####  5. EDA with famous baby name dataset (3 pts)

For downloading the data set go to [https://www.ssa.gov/oact/babynames/state/namesbystate.zip]
or use [this box link](https://app.box.com/s/i52qu3mgmpwvikiggjmwwydgycw4d4bt) to access all the text files.

1. How many men and women were counted?
2. Count unique boy/girl names.
3. Find top 10 popular names between 2000 - 2015 and plot their trend 
4. Create a new column titled namelength ( you can use str.len()). Then plot the averge length of names


In [7]:
# Your code goes here 

In [8]:
# Your code goes here 